freebsd_instance:
  image: freebsd-12-3-release-amd64
  
env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[c976a5fd009f82ce665915aebde143a38cc3fba7f186866e70ba0f5e2dc5e9e95b642fff9af5b000e70d1e703688fb93]
  CCACHE_DIR: "/tmp/.ccache"
  CCACHE_COMPRESS: 1
  CCACHE_SIZE: "200M"
  CCACHE_STATIC_PREFIX: "/usr/local"
  CCACHE_NOSTATS: 1
  CCACHE_TEMPDIR: "/tmp"
  WITH_CCACHE_BUILD: "YES"
ccache_cache:
  folder: ${CCACHE_DIR}
pkg_cache:
  folder: /var/cache/pkg/
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-3-release-amd64
  stateful: false
  setup_script:
    - sed -i '' -e 's|quarterly|release_4|g' "/etc/pkg/FreeBSD.conf" # https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270940
    - pkg install -y git-lite curl wget zip cmake pkgconf qt5-core qt5-widgets qt5-multimedia qt5-qmake qt5-buildtools meson zstd
  ccache_setup_script:
    - env IGNORE_OSVERSION=yes pkg install -y ccache-static
    - ccache --max-size=${CCACHE_SIZE}
    - echo "WITH_CCACHE_BUILD=yes" >> /etc/make.conf
  test_script:
    - git submodule update --init --recursive
    - git clone https://github.com/Gottox/libsqsh
    - cd libsqsh
    - git checkout v1.0.0
    - meson setup build -Dwerror=false -Dexamples=false -Dcurl=disabled -Dzlib=enabled -Dlz4=disabled -Dlzma=disabled -Dzstd=enabled -Dthreads=enabled -Ddoc=false
    - cd build
    - meson compile
    - sudo meson install
    - cd ../../
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make DESTDIR=. -j$(sysctl -n hw.ncpu) install
    - find Filer.app/
    - ( zip --symlinks -r ./Filer_FreeBSD.zip Filer.app/ )
    - case "$CIRRUS_BRANCH" in *pull/*) echo "Skipping since it's a pull request" ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; fetch https://github.com/probonopd/continuous-release-manager/releases/download/continuous/continuous-release-manager-freebsd && chmod +x continuous-release-manager-freebsd && ./continuous-release-manager-freebsd && ./ghr -replace -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
