image: ubuntu:20.04

tasks:
    - name: dependencies
      # Install dependencies as defined in GitHub Actions
      command: |
          cat .github/workflows/ubuntu.yml | grep "sudo apt-get install" | xargs | sh
